### PR TITLE
Update to 0.0.20

### PR DESCRIPTION
**Pull request by 3laws**
🙋‍‍♂️

### CODE REVIEW

**Comment by DarkJoij** [comment]
Yes, please

**Comment by erentar** [comment]
It has been a good week since this package broke

**Comment by 3laws** [comment]
@DarkJoij @erentar I've published the RPM under releases in my fork. In case you don't want to build the RPM from it.

**Comment by kwizart** [comment]
It was built in 15/09/2022 and pushed to stable updates

dnf update --refresh

**Comment by kwizart** [comment]
(I've just restored the package sync commit to github).

**Comment by kwizart** [comment]
Side note, for anyone willing to contribute directly to RPM Fusion, please see:
https://rpmfusion.org/Contributors

I hope this still a good opportunity to learn packaging...

**Comment by sergiomb2** [comment]
hello please follow 
 https://bugzilla.rpmfusion.org/show_bug.cgi?id=5953#c30 

you got the build several days ago , we are waiting to be published soon

**Comment by sergiomb2** [comment]
please add you as CC to that bug report and you can get updates sooner

**Pull request closed without merging**
