### PR TITLE
Update to 0.0.19

### PR DESCRIPTION
**Pull request by Justinzobel**

### CODE REVIEW

**Comment by Justinzobel** [comment]
Tested on F36, running OK.

**Comment by k2helix** [comment]
Shouldn't something in the sources file change?

**Comment by dutsky** [comment]
works for me too, without any changes. @Justinzobel maybe `sources` file must be updated too?

**Comment by dutsky** [comment]
@sergiomb2 can you check this PR, please? From today `discord` can't start if its version is `0.0.18`, it's just say "please update your version" and exits, allowing you to download tar.gz or deb file.

**Comment by 24online24** [comment]
Hope this gets accepted soon. As dutsky said, the current version prompts you to update (.deb and .tar.gz versions) or closes if you don't.
image
image

**Comment by Fatih120** [comment]
I hate Discord so much. It doesn't even force you to update immediately on Windows. Hate this awful software demon spawn I hope people stop flooding over to it so I never have to use it again.

**Comment by sergiomb2** [comment]
Hi, thank you for ping me 

please follow 
https://bugzilla.rpmfusion.org/show_bug.cgi?id=5953#c26

**Pull request merged**
