### PR TITLE
Update discord to 0.0.26

### PR DESCRIPTION
**Pull request by dotterian**
Speeding up a moment when I'll get fresh version from repo :wink:

### CODE REVIEW

**Comment by erentar** [comment]
Who is in charge of accepting this merge?
They are clearly not doing a good job

**Comment by kwizart** [comment]
None is, stricly speaking one has to submit a ticket in our bug tracking system to notice the maintainer.
Also co-maintainer are welcomed.

PR are only kept for ease, but do not participate in reporting to the appropriate maintainer (blame free github restrictions).

For clarity, this PR is already accepted (or an equivalent).
https://koji.rpmfusion.org/koji/packageinfo?packageID=537


Also due to the nature of discord, you will often find a delay with updates, so you need to have a acc

**Comment by sergiomb2** [comment]
I did apply with my automated script 
https://pkgs.rpmfusion.org/cgit/nonfree/discord.git/commit/?id=bcb6b884796594c8ade29c4f6a217918ebea674b

please follow the bug report https://bugzilla.rpmfusion.org/show_bug.cgi?id=5953 

note that If you edit this file (or create it if it doesn't exist): ~/.config/discord/settings.json

To add this: "SKIP_HOST_UPDATE": true

It will allow you to launch it, even if its out of date.

**Comment by miry** [comment]
@sergiomb2 I see the commit is already in master branch. In same time when I try to run `sudo dnf update discord` for Fedora 37 it still shows discord-0.0.25-1.fc37.
I am still new in linux and fedora, do you know how I can debug the problem?

**Comment by sergiomb2** [comment]
> @sergiomb2 I see the commit is already in master branch. In same time when I try to run `sudo dnf update discord` for Fedora 37 it still shows discord-0.0.25-1.fc37. I am still new in linux and fedora, do you know how I can debug the problem?


after build in koji , it will be publish on repos when is manually pushed by one admin and we got one email with RPMFusion update report day n 

to workaround this delay, you may install it directly from koji see https://bugzilla.rpmfusion.org/show_bug.cgi?id=5953#c47

**Comment by miry** [comment]
@sergiomb2 That make sense. Sorry that I have not read exactly for this trick in previous message. The settings for discord is working like a charm.

**Comment by LinuxDonald** [comment]
Please update to 0.0.36

**Comment by sergiomb2** [comment]
Thank you used my helper script to update it , you may close the PR

**Comment by valmerax** [comment]
Hi, i'm interested to know if there is the possibility of natively integrating the "SKIP_HOST_UPDATE" solution into rpm in order to avoid have the application blocked while waiting for the update to be available in the repositories.

I participated in reporting the issue on the rpmfusion bugzilla ([Bug 6841](https://bugzilla.rpmfusion.org/show_bug.cgi?id=6841)) but I don't know if @seancallaway is still active.

I have since created a shell script of my own to try to solve this problem natively, and after some research I found that it could be integrated as a patch directly into the postinstall.sh of the rpm.

@sergiomb2, I saw in a previous comment that you had also developed a script on this subject, hence my question, is there a particular reason that could prevent this solution from being implemented to the rpm ?

**Comment by kwizart** [comment]
Closing this older PR.

**Pull request closed without merging**
