### PR TITLE
Update discord to 0.0.24

### PR DESCRIPTION
**Pull request by OliverGeneser**

### CODE REVIEW

**Comment by sergiomb2** [comment]
thank you , building now , I just merged yours commit because sources files aren't correct

**Comment by OliverGeneser** [comment]
@sergiomb2 My mistake... I just fixed the source file

**Comment by sergiomb2** [comment]
builds are already available https://bugzilla.rpmfusion.org/show_bug.cgi?id=5953#c41

**Comment by arimgibson** [comment]
Not sure if it's related, but dnf doesn't want to find the 0.0.24 version, even though I am seeing it built on [RPMFusion](https://koji.rpmfusion.org/koji/packageinfo?packageID=537). Could it be because of the source? Was able to use the information at the bugzilla you provided @sergiomb2 to get the right version though :smile:

Fedora 37, can see that the most recent version found by rpmfusion is 0.0.23
```
[root@fedora ari]# dnf list --showduplicates discord --refresh
(refreshing all repos)
Installed Packages
discord.x86_64                                 0.0.24-1.fc37                                 @@commandline            
Available Packages
discord.x86_64                                 0.0.21-1.fc37                                 rpmfusion-nonfree        
discord.x86_64                                 0.0.23-1.fc37                                 rpmfusion-nonfree-updates

```

**Comment by sergiomb2** [comment]
is not yet published , please follow https://bugzilla.rpmfusion.org/show_bug.cgi?id=5953#c41 

use one of this updates , first is for rawhide , second is for f37 and 3rd is for f36 



```
dnf update https://koji.rpmfusion.org/kojifiles/packages/discord/0.0.24/1.fc38/x86_64/discord-0.0.24-1.fc38.x86_64.rpm -y 

dnf update https://koji.rpmfusion.org/kojifiles/packages/discord/0.0.24/1.fc37/x86_64/discord-0.0.24-1.fc37.x86_64.rpm -y 

dnf update https://koji.rpmfusion.org/kojifiles/packages/discord/0.0.24/1.fc36/x86_64/discord-0.0.24-1.fc36.x86_64.rpm -y
```

**Comment by arimgibson** [comment]
Gotcha, didn't realize that the builds weren't published automatically. Out of curiosity, what additional steps are required for publishing? Does it have to be reviewed or something?

**Comment by sergiomb2** [comment]
the packages are published by admins one or two times per week , so we just need to wait 

you got one email report on user and devel mailing list for example : 
 https://lists.rpmfusion.org/archives/list/rpmfusion-users@lists.rpmfusion.org/thread/3FNT3LAGBV66VTC3LHYBYJ6GJHDJKXVJ/

**Comment by CRCinAU** [comment]
We're now at 0.0.25 and haven't been able to use Discord for a few days now...

Is there a way to streamline this process on updates? It seems to be suboptimal to be locked out of Discord for several days waiting for each update.

**Comment by sergiomb2** [comment]
Please follow https://bugzilla.rpmfusion.org/show_bug.cgi?id=5953 , updates are announced there .

BTW 
If you edit this file (or create it if it doesn't exist): ~/.config/discord/settings.json

To add this: "SKIP_HOST_UPDATE": true

It will allow you to launch it, even if its out of date.

**Comment by CRCinAU** [comment]
> To add this: "SKIP_HOST_UPDATE": true
> 
> It will allow you to launch it, even if its out of date.

That is an *AWESOME* hint. I wish that it was more well known - as its a pain that discord locks you out if you don't have the latest version.

Thanks.

**Comment by kwizart** [comment]
Worth to document this config option into our wiki. (will tweet about it).

**Pull request closed without merging**
